import PageScanner  from './PageScanner';
let pm= new PageScanner();
import * as from '../../../common/build/infox';
const pugrender  = require('hpug');
const template = require('./template.pug');
declare var __projRootDir:string;
declare var __globalDirsMap:DirectoriesMap;
let fpages = pm.getFPages();
const data = pugrender.getData();
data.fpages = fpages;
data.fp_len = fpages.length;
module.exports = template(data);