import * as path from 'path';
export const rootDir =  path.resolve(__dirname,"..","..");
export const outputDir= path.resolve(rootDir + "dist");
export const srcDir = path.resolve(rootDir , "src");
export const scriptsDir = path.resolve(rootDir , "src/scripts");
export const entriesDir = path.resolve(rootDir , "src/entries");
export const jadesDir = path.resolve(rootDir , "src/templates");
export const assestesDir = path.resolve(rootDir , "src/assests");
export const cssDir = path.resolve(rootDir , "src/css");
export const dataDir = path.resolve(rootDir , "src/data");
