import * as path from 'path';
export const rootDir =  path.resolve(__dirname,"..","..");
export const outputDir= path.resolve(rootDir,"dist");
export const srcDir = path.resolve(rootDir , "src");
export const commonDir = path.resolve(srcDir , "common");
export const pagesDir = path.resolve(srcDir , "pages");
export const entriesDir = path.resolve(srcDir , "entries");
export const jadesDir = path.resolve(srcDir , "templates");
export const assestesDir = path.resolve(srcDir , "assests");
export const cssDir = path.resolve(srcDir , "css");
export const dataDir = path.resolve(srcDir , "data");
